-- Migration 0002: better-auth tables + rate_limit
-- Generated by hand from better-auth getAuthTables() output (email-otp plugin).
-- Read before applying:
--   - "user" table is better-auth's identity table, separate from app "users" table.
--   - "session" and "account" use camelCase column names as better-auth expects.
--   - "verification" stores OTP codes (value field, expires 10 min).
--   - "rate_limit" is our own table for IP/email request tracking.

-- better-auth: user identity table
CREATE TABLE "ba_user" (
    "id" text PRIMARY KEY NOT NULL,
    "name" text NOT NULL,
    "email" text NOT NULL,
    "emailVerified" boolean NOT NULL DEFAULT false,
    "image" text,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "ba_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint

-- better-auth: session table (database-backed, revocable)
CREATE TABLE "session" (
    "id" text PRIMARY KEY NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    "token" text NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "ipAddress" text,
    "userAgent" text,
    "userId" text NOT NULL,
    CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint

-- better-auth: account table (provider accounts)
CREATE TABLE "account" (
    "id" text PRIMARY KEY NOT NULL,
    "accountId" text NOT NULL,
    "providerId" text NOT NULL,
    "userId" text NOT NULL,
    "accessToken" text,
    "refreshToken" text,
    "idToken" text,
    "accessTokenExpiresAt" timestamp with time zone,
    "refreshTokenExpiresAt" timestamp with time zone,
    "scope" text,
    "password" text,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- better-auth: verification table (stores OTP codes via email-otp plugin)
CREATE TABLE "verification" (
    "id" text PRIMARY KEY NOT NULL,
    "identifier" text NOT NULL,
    "value" text NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- Our rate-limit table (no Redis — a counter row is correct at this scale)
-- UNIQUE(key, window_start): one counter row per key per hour window. The
-- upsert in server/services/rate-limit.ts depends on this constraint; without
-- it every request inserts a fresh row and the limit never fires.
CREATE TABLE "rate_limit" (
    "id" bigserial PRIMARY KEY NOT NULL,
    "key" text NOT NULL,
    "count" integer NOT NULL DEFAULT 1,
    "window_start" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "rate_limit_key_window_unique" UNIQUE("key", "window_start")
);
--> statement-breakpoint

-- Foreign keys
ALTER TABLE "session"
    ADD CONSTRAINT "session_userId_ba_user_id_fk"
    FOREIGN KEY ("userId") REFERENCES "ba_user"("id") ON DELETE cascade;
--> statement-breakpoint

ALTER TABLE "account"
    ADD CONSTRAINT "account_userId_ba_user_id_fk"
    FOREIGN KEY ("userId") REFERENCES "ba_user"("id") ON DELETE cascade;
--> statement-breakpoint

-- Indexes
CREATE INDEX "session_userId_idx" ON "session" ("userId");
--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "account" ("userId");
--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" ("identifier");
--> statement-breakpoint
-- Partial index: only live windows matter for rate-limit lookups
CREATE INDEX "rate_limit_key_idx" ON "rate_limit" ("key", "window_start");
